# Generated by Django 6.0.1 on 2026-01-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('service', models.CharField(choices=[('custom_website', 'Custom Website Development'), ('shopify', 'Shopify Store Development'), ('wordpress', 'WordPress Website'), ('redesign', 'Website Redesign'), ('maintenance', 'Maintenance & Support'), ('seo', 'SEO & Optimization'), ('other', 'Other Services')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='New', max_length=20)),
            ],
        ),
    ]
