# Generated by Django 5.2.3 on 2026-01-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
